[package]
name = "rust_rendering"
version = "0.1.0"
authors = ["Nolann <nolann.juet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.27.0"